Hardcode OID
wolfSSL/wolfProvider pull request #57
Opened 2024-11-21 17:18 UTC by bandi13

Set the OID of the Signature Algorithm to sha256WithRSAEncryption.

2024-11-22 15:00 UTC, bandi13 commented
retest this please

2024-11-27 22:09 UTC, SparkiDev requested changes

2024-11-27 22:09 UTC, SparkiDev commented on src/wp_rsa_sig.c
> +    const byte oid[] = {0x30, 0x0b, 0x06, 0x09, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01, 0x0b, 0x05, 0x00, 0x04, 0x10};
Which OID is this?
Rename variable.
(We should have more but if this fixes the customer's issue then we'll leave the TOOD.)

2024-12-10 02:29 UTC, SparkiDev approved these changes

2024-12-12 21:49 UTC, SparkiDev approved these changes

2024-12-12 21:49 UTC, SparkiDev commented
retest this please

2024-12-12 22:14 UTC, merged