Initial implementation of DES3 for wolfprovider
wolfSSL/wolfProvider pull request #58
Opened 2024-12-18 21:43 UTC by ColtonWilley

Initial implementation of DES3 for wolfProvider.

Fixes ZD 18906

2025-01-06 23:25 UTC, SparkiDev commented
retest this please

2025-02-12 22:44 UTC, SparkiDev requested changes
Add tests.

2025-02-12 22:44 UTC, SparkiDev commented on src/wp_des.c
> +/**                                                                            \
Fix formatting

2025-02-17 18:02 UTC, ColtonWilley commented
> Add tests.

@SparkiDev There were already existing 3DES tests, they simply never ran. They now run and pass against the new implementation.

2025-02-17 22:10 UTC, SparkiDev approved these changes

2025-02-17 22:10 UTC, merged